# =============================================================================
# FZF (Fuzzy Finder) CONFIGURATION
# =============================================================================
# fzf is a general-purpose command-line fuzzy finder.
#
# KEY BINDINGS (when fzf shell integration is loaded):
#   Ctrl-T  - Fuzzy file search and insert into command line
#   Ctrl-R  - Fuzzy command history search
#   Alt-C   - Fuzzy directory browser and cd (requires terminal to send Alt as Meta)
#   Ctrl-G  - Same as Alt-C (fallback if Alt key doesn't work)
#
# WHY source ~/.fzf.zsh instead of /opt/homebrew/.../key-bindings.zsh:
#   - ~/.fzf.zsh is generated by fzf install script
#   - Uses `source <(fzf --zsh)` which loads both completion AND key bindings
#   - Handles upgrades automatically when you re-run `$(brew --prefix)/opt/fzf/install`
# =============================================================================

# ------------------------------------------------------------------------------
# FZF Default Options
# ------------------------------------------------------------------------------
# WHY: Set consistent behavior across all fzf invocations.
#   --height 40%: Use 40% of terminal height (vs full screen)
#   --layout=reverse: Show prompt at top (matches common习惯)
#   --bind ctrl-j:down,ctrl-k:up: Vim-style navigation in fzf
# ------------------------------------------------------------------------------
export FZF_DEFAULT_OPTS='
  --height 40%
  --layout=reverse
  --bind=ctrl-j:down
  --bind=ctrl-k:up
  --bind=ctrl-d:half-page-down
  --bind=ctrl-u:half-page-up
'

# ------------------------------------------------------------------------------
# FZF Shell Integration
# ------------------------------------------------------------------------------
# Loads fzf key bindings (Ctrl-T, Ctrl-R, Alt-C) and fuzzy completion
# Requires ~/.fzf.zsh which is created by: $(brew --prefix)/opt/fzf/install
# ------------------------------------------------------------------------------
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ------------------------------------------------------------------------------
# Alt+C Troubleshooting
# ------------------------------------------------------------------------------
# If Alt+C produces a special character (like Ç) instead of opening fzf:
#   1. Terminal is not sending Alt as Meta/escape prefix
#   2. Test: Press Ctrl+V then Alt+C - should see ^[c not Ç
#   3. Fix: Configure terminal to send Alt as Meta, or use Ctrl+G instead
#   4. WezTerm: Add to ~/.wezterm.lua keys:
#        { key = "c", mods = "ALT", action = wezterm.action.SendKey { key = "c", mods = "META" } }
# ------------------------------------------------------------------------------
